# Modul 1 Praktikum Data Mining 
## Manipulasi array menggunakan numpy
* Hartawan Bahari Mulyadi
* Student ID: 182410101113


In [1]:
# Init Library
import numpy as np
def sep(text = ''):
  if text == '':
    text = "-"
  else:
    text = "["+text+"]"
  print("=-=-=-=-=-="+text+"=-=-=-=-=-=")
def br():
  print('')

## KODE 1

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
#a.	Jelaskan fungsi dari library numpy
#b.	Jelaskan perbedaan numpy dengan list pada python
#c.	Jelaskan tentang ndarray
#d.	Jelaskan fungsi baris 1
#e.	Jelaskan fungsi baris 2


[1 2 3 4 5]


<img
src="https://webcourses.ucf.edu/courses/1249560/files/64324060/download?verifier=ZSNNql7AkXjfNQuAPKVykvZTiRqAa6LJY4EvPrdr&wrap=1" width = "400" align = "center">
__<< PYTHON LIST__
<img
src="https://webcourses.ucf.edu/courses/1249560/files/64324040/download?verifier=V7pAn7JWwOOMUVR8nJ2mpRIfu8MRFGTSZNwUCAlq&wrap=1" width = "400" align = "center">
__<< NUMPY ARRAY__



Double-click __here__ for show reference.

<!-- The Reference:
    
https://webcourses.ucf.edu/courses/1249560/pages/python-lists-vs-numpy-arrays-what-is-the-difference#:~:text=A%20numpy%20array%20is%20a,a%20tuple%20of%20nonnegative%20integers.&text=A%20list%20is%20the%20Python,The%20answer%20is%20performance.

-->

In [3]:
# SOAL F
# Buatlah array 2D berikut menggunakan numpy
matrix_1qf = np.array([[4,4,5],[7,6,4],[9,7,4],[6,3,7]])
print(matrix_1qf)

[[4 4 5]
 [7 6 4]
 [9 7 4]
 [6 3 7]]


In [4]:
# SOAL G
# Buatlah array 3D berikut menggunakan numpy
matrix_1g = np.array([
                [[7, 8, 5], [4, 7, 7], [7,1,9], [5,4,10]],
                [[2, 1, 2], [9, 8, 5], [3,7,3], [4,9,9]],
                [[2,9,3], [2, 4, 8], [1,6,6], [8,1,3]],
                ])
print(matrix_1g)

[[[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]]


## KODE 2

In [5]:
import numpy as np #this line is useless
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2]) #line 3

import numpy as np #this line is useless
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4]) #line 7

import numpy as np #this line is useless
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2]) #line10


#a.	Jelaskan cara mengakses elemen array seperti kode pada baris 3
#b.	Jelaskan cara mengakses elemen array seperti kode pada baris 7
#c.	Jelaskan cara mengakses elemen array seperti kode pada baris 10


6
[1 2 3 4]
[3 8]


In [6]:
# SOAL D
# Tambahkan angka 1 pada setiap bilangan di baris ganjil array berikut. 
# kemudian tambahkan angka 2 pada setiap bilangan di kolom genap array berikut.
matrix_2d = np.array([
                        [1,8,8,2],
                        [8,2,1,2],
                        [10,1,4,7],
                        [1,4,7,8],
                        [8,2,3,4]])
sep("Orgiginal")
print(matrix_2d)
sep("Add 1 every Row")
matrix_2d[::2] +=1 #baris ganjil
print(matrix_2d)
sep("Add 2 every Column")
matrix_2d[:, 1::2]+=2 #genap
print(matrix_2d)



=-=-=-=-=-=[Orgiginal]=-=-=-=-=-=
[[ 1  8  8  2]
 [ 8  2  1  2]
 [10  1  4  7]
 [ 1  4  7  8]
 [ 8  2  3  4]]
=-=-=-=-=-=[Add 1 every Row]=-=-=-=-=-=
[[ 2  9  9  3]
 [ 8  2  1  2]
 [11  2  5  8]
 [ 1  4  7  8]
 [ 9  3  4  5]]
=-=-=-=-=-=[Add 2 every Column]=-=-=-=-=-=
[[ 2 11  9  5]
 [ 8  4  1  4]
 [11  4  5 10]
 [ 1  6  7 10]
 [ 9  5  4  7]]


In [11]:
# SOAL E
# Baliklah sumbu z array 3D berikut
matrix_2e = np.array([
                      [[7,8,5], [4,7,7],[7,1,9],[5,4,10]],
                      [[2,1,2],[9,8,5],[3,7,3],[4,9,9]],
                      [[2,9,3],[2,4,8],[1,6,6],[8,1,3]]])
sep("Orgiginal")
print(matrix_2e)
sep("Transpose")
print(matrix_2e.T)
sep("Transpose alternative")
print(np.transpose(matrix_2e))
sep("z-transpose")
print(matrix_2e.transpose(2,0,1))
sep()
print(matrix_2e.transpose(2,1,0))

=-=-=-=-=-=[Orgiginal]=-=-=-=-=-=
[[[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]]
=-=-=-=-=-=[Transpose]=-=-=-=-=-=
[[[ 7  2  2]
  [ 4  9  2]
  [ 7  3  1]
  [ 5  4  8]]

 [[ 8  1  9]
  [ 7  8  4]
  [ 1  7  6]
  [ 4  9  1]]

 [[ 5  2  3]
  [ 7  5  8]
  [ 9  3  6]
  [10  9  3]]]
=-=-=-=-=-=[Transpose alternative]=-=-=-=-=-=
[[[ 7  2  2]
  [ 4  9  2]
  [ 7  3  1]
  [ 5  4  8]]

 [[ 8  1  9]
  [ 7  8  4]
  [ 1  7  6]
  [ 4  9  1]]

 [[ 5  2  3]
  [ 7  5  8]
  [ 9  3  6]
  [10  9  3]]]
=-=-=-=-=-=[z-transpose]=-=-=-=-=-=
[[[ 7  4  7  5]
  [ 2  9  3  4]
  [ 2  2  1  8]]

 [[ 8  7  1  4]
  [ 1  8  7  9]
  [ 9  4  6  1]]

 [[ 5  7  9 10]
  [ 2  5  3  9]
  [ 3  8  6  3]]]
=-=-=-=-=-=-=-=-=-=-=-=
[[[ 7  2  2]
  [ 4  9  2]
  [ 7  3  1]
  [ 5  4  8]]

 [[ 8  1  9]
  [ 7  8  4]
  [ 1  7  6]
  [ 4  9  1]]

 [[ 5  2  3]
  [ 7  5  8]
  [ 9  3  6]
  [10  9  3]]]


In [8]:
# KODE F
# Ubahlah array pada soal e menjadi array 2D berukuran 6 x 6 (hint : gunakan perintah reshape)
sep("Original")
print(matrix_2e)
sep("Sliced")
print(matrix_2e.reshape([6,6]))

=-=-=-=-=-=[Original]=-=-=-=-=-=
[[[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]]
=-=-=-=-=-=[Sliced]=-=-=-=-=-=
[[ 7  8  5  4  7  7]
 [ 7  1  9  5  4 10]
 [ 2  1  2  9  8  5]
 [ 3  7  3  4  9  9]
 [ 2  9  3  2  4  8]
 [ 1  6  6  8  1  3]]


## KODE 3

In [9]:
import numpy as np #this line is useless
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]]) #line 3
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)
br()
import numpy as np #this line is useless
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1) #line 9
print(newarr)
# a.	Jelaskan apa yang dilakukan di baris 3
# b.	Gantilah nilai axis menjadi 0. Jelaskan apa yang terjadi
sep("Question B")
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)
br()
# c.	Jelaskan apa yang dilakukan di baris 9
# d.	Gantilah nilai axis menjadi 0. Jelaskan apa yang terjadi
sep("Question D")
newarr = np.array_split(arr, 3, axis=0)
print(newarr)
br()

[[1 2 5 6]
 [3 4 7 8]]

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
=-=-=-=-=-=[Question B]=-=-=-=-=-=
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

=-=-=-=-=-=[Question D]=-=-=-=-=-=
[array([[1, 2],
       [3, 4]]), array([[5, 6]]), array([[7, 8]])]



In [13]:
# SOAL E
# Ubahlah matris kiri menjadi matriks sebelah kanan
matrix_3e = np.array([
                        [5,10,10,7],[7,8,4,10],[9,10,2,5],[1,8,9,3],[6,10,5,2],[4,6,9,4] ])
matrix_3e_goal = np.array([
                        [9,3,1,8],[5,2,6,10],[9,4,4,6],[10,7,5,10],[4,10,7,8],[2,5,9,10] ])
sep("Goal")
print(matrix_3e_goal)
sep("Original")
print(matrix_3e)
br()
sep("Answer")
# | H0T | H1T |
# | H0B | H1B |
# *ps: axis 0 (y = ↓)      axis 1 (x=→)
H0 = np.split(matrix_3e,2, axis=1)[0] 
H0T = np.split(H0,2, axis=0)[0]
H0B = np.split(H0,2, axis=0)[1]
H1 = np.split(matrix_3e,2, axis=1)[1]
H1T = np.split(H1,2, axis=0)[0]
H1B = np.split(H1,2, axis=0)[1]
#print(H0T)
#print(H0B)
# br()
#print(H1T)
#print(H1B)
H0 = np.concatenate((H1B, H0B), axis=1)
H1 = np.concatenate((H1T, H0T), axis=1)
goal = np.concatenate((H0, H1), axis=0)

sep()
print(H0)
sep()
print(H1)
print(goal)

=-=-=-=-=-=[Goal]=-=-=-=-=-=
[[ 9  3  1  8]
 [ 5  2  6 10]
 [ 9  4  4  6]
 [10  7  5 10]
 [ 4 10  7  8]
 [ 2  5  9 10]]
=-=-=-=-=-=[Original]=-=-=-=-=-=
[[ 5 10 10  7]
 [ 7  8  4 10]
 [ 9 10  2  5]
 [ 1  8  9  3]
 [ 6 10  5  2]
 [ 4  6  9  4]]

=-=-=-=-=-=[Answer]=-=-=-=-=-=
=-=-=-=-=-=-=-=-=-=-=-=
[[ 9  3  1  8]
 [ 5  2  6 10]
 [ 9  4  4  6]]
=-=-=-=-=-=-=-=-=-=-=-=
[[10  7  5 10]
 [ 4 10  7  8]
 [ 2  5  9 10]]
[[ 9  3  1  8]
 [ 5  2  6 10]
 [ 9  4  4  6]
 [10  7  5 10]
 [ 4 10  7  8]
 [ 2  5  9 10]]
